#!/bin/bash

# Путь к текущему скрипту
SCRIPT_PATH=$(realpath "$0")

# Директория для резервных копий
BACKUP_DIR="$HOME/backup"

# Создание директории для резервных копий, если она не существует
mkdir -p "$BACKUP_DIR"

# Имя файла без пути
SCRIPT_NAME=$(basename "$SCRIPT_PATH")

# Имя и путь резервного архива
BACKUP_FILE="$BACKUP_DIR/${SCRIPT_NAME}.tar.gz"

# Создание архива с резервной копией
tar -czvf "$BACKUP_FILE" -C "$(dirname "$SCRIPT_PATH")" "$SCRIPT_NAME"

echo "Резервная копия создана: $BACKUP_FILE"
